# --- Base Path ---
# verbose: whether to print out module details or not
# ----------------- 
verbose: True 

# --- Data Path ---
# data_sample: input file (.jsonl format)
# content: each file should have a text, and optionally id and label columns
# ----------------- 
data_sample: "backend/data/input/sentences.jsonl"

# --- Generation ---
# prompt: prompt to generate 1st-level topics
# seed: seed topics (TODO: modify to fit your conception of the data)
# output: output file containing texts and their corresponding generated topics
# topic_output: md file containing all generated topics
# ----------------- 
generation:
  prompt: "backend/prompt/A/generation_discussion_1_A.txt"
  seed: "backend/prompt/A/seed.md"      
  output: "backend/out/generation1output.jsonl"
  topic_output: "backend/out/gen1topicout.md"



# --- Refinement ---
# refining_topics: whether to refine topics or not
# prompt: prompt to merge near duplicate topics
# output: output file, with an added refined_responses columns that replaces all removed/merged topics with the corresponding new topic
# topic_output: md file containing the list of refined topics
# mapping: mapping between originally generated topics and the topic they have been merged to
# remove: whether to remove topics with low frequency (occurring <1% of the time)
refining_topics: True
refinement:
  prompt: "backend/prompt/refinement.txt"
  output: "backend/out/refinement.jsonl"
  topic_output: "backend/out/refinement.md"
  mapping_file: "backend/out/refinement_mapping.json"
  remove: True      


# --- Subtopic Generation ---
# generate_subtopics: whether to generate subtopics or not
# prompt: prompt to generate subtopic to each high-level topic, given some example documents that correspond to that high-level topic
# output: output file containing texts and their corresponding high-level and low-level topics
# topic_output: md file containing topic tree
# ---------------------------
generate_subtopics: False
generation_2:
  prompt: "prompt/A/generation_discussion_2_A.txt"
  output: "out/generation_2_4.jsonl"
  topic_output: "out/generation_2_4.md"

# --- Assignment ---
# prompt: prompt to assign topics to documents
# output: output of topic assignment
# ------------------
assignment:
  prompt: "backend/prompt/assignment.txt"
  output: "backend/out/properAssign.jsonl"


# --- Correction ---
# prompt: prompt to correct topics
# output: output of topic correction
# ------------------
correction:
  prompt: "backend/prompt/correction.txt"
  output: "backend/out/assignment_corrected.jsonl"


# --- Comparison ---
# ------------------
generate_comparison: True
comparison:
  prompt: "backend/prompt/A/generation_A.txt"
  output: "backend/comparisons/4.jsonl"

# --- Baseline ---
# ------------------
baseline:
  prompt: "backend/prompt/A/baseline.txt"
  output: "backend/baseline/4.jsonl"


# --- Evaluate ---
# ------------------
evaluate:
  prompt: "backend/prompt/A/evaluate.txt"
  output: "evaluate/4.jsonl"


